version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # expose to host only if needed
      - "5432:5432"

  backend:
    build:
      context: ./backend-gym-api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend-gym-api/.env.backend
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./fitness-nexus-saas
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    env_file:
      - ./fitness-nexus-saas/.env.frontend
    environment:
      # override inside docker so frontend talks to backend container
      VITE_API_URL: http://backend:8000
      REACT_APP_API_URL: http://backend:8000
    ports:
      - "3000:80"

volumes:
  postgres_data:
